# Generated by Django 4.0.2 on 2022-03-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='bike name')),
                ('price', models.CharField(blank=True, max_length=60, null=True, verbose_name='bike price')),
                ('top_speed', models.CharField(max_length=60, verbose_name='top speed')),
                ('range', models.CharField(max_length=60, verbose_name='range')),
                ('charging_time', models.CharField(max_length=60, verbose_name='charging time')),
                ('colors', models.CharField(blank=True, max_length=60, null=True, verbose_name='colors')),
                ('rating', models.CharField(blank=True, max_length=60, null=True, verbose_name='rating')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('images', models.URLField(blank=True, null=True, verbose_name='images')),
                ('offers', models.CharField(blank=True, max_length=180, null=True, verbose_name='offers')),
                ('battery_type', models.CharField(blank=True, max_length=180, null=True, verbose_name='battery type')),
                ('weight', models.CharField(blank=True, max_length=180, null=True, verbose_name='weight')),
                ('speedometer', models.CharField(blank=True, max_length=180, null=True, verbose_name='speedometer')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='car name')),
                ('price', models.CharField(blank=True, max_length=60, null=True, verbose_name='car price')),
                ('top_speed', models.CharField(max_length=60, verbose_name='top speed')),
                ('range', models.CharField(max_length=60, verbose_name='range')),
                ('charging_time', models.CharField(max_length=60, verbose_name='charging time')),
                ('colors', models.CharField(blank=True, max_length=60, null=True, verbose_name='colors')),
                ('rating', models.CharField(blank=True, max_length=60, null=True, verbose_name='rating')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('images', models.URLField(blank=True, null=True, verbose_name='images')),
                ('offers', models.CharField(blank=True, max_length=180, null=True, verbose_name='offers')),
                ('battery_type', models.CharField(blank=True, max_length=180, null=True, verbose_name='battery type')),
                ('max_power', models.CharField(blank=True, max_length=180, null=True, verbose_name='max power')),
            ],
        ),
        migrations.CreateModel(
            name='Scooters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='scooter name')),
                ('price', models.CharField(blank=True, max_length=60, null=True, verbose_name='scooter price')),
                ('top_speed', models.CharField(max_length=60, verbose_name='top speed')),
                ('range', models.CharField(max_length=60, verbose_name='range')),
                ('charging_time', models.CharField(max_length=60, verbose_name='charging time')),
                ('colors', models.CharField(blank=True, max_length=60, null=True, verbose_name='colors')),
                ('rating', models.CharField(blank=True, max_length=60, null=True, verbose_name='rating')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='description')),
                ('images', models.URLField(blank=True, null=True, verbose_name='images')),
                ('offers', models.CharField(blank=True, max_length=180, null=True, verbose_name='offers')),
                ('battery_type', models.CharField(blank=True, max_length=180, null=True, verbose_name='battery type')),
                ('weight', models.CharField(blank=True, max_length=180, null=True, verbose_name='weight')),
                ('speedometer', models.CharField(blank=True, max_length=180, null=True, verbose_name='speedometer')),
            ],
        ),
    ]
