# Generated by Django 4.0.2 on 2022-03-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0002_rename_bikes_bike_rename_cars_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='images',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='car',
            name='images',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='images',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='images'),
        ),
    ]
