# Generated by Django 4.0.2 on 2022-03-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0003_alter_bike_description_alter_bike_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='images',
        ),
        migrations.AddField(
            model_name='car',
            name='frontimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='car',
            name='rearimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
        migrations.AddField(
            model_name='car',
            name='sideimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='bike',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
