# Generated by Django 4.0.2 on 2022-03-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0004_remove_car_images_car_frontimg_car_rearimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='frontimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/cars'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rearimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/cars'),
        ),
        migrations.AlterField(
            model_name='car',
            name='sideimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/cars'),
        ),
    ]
