# Generated by Django 4.0.2 on 2022-03-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0005_alter_car_frontimg_alter_car_rearimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='images',
        ),
        migrations.AddField(
            model_name='bike',
            name='frontimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/bikes'),
        ),
        migrations.AddField(
            model_name='bike',
            name='rearimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/bikes'),
        ),
        migrations.AddField(
            model_name='bike',
            name='sideimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/bikes'),
        ),
    ]
