# Generated by Django 4.0.2 on 2022-03-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0006_remove_bike_images_bike_frontimg_bike_rearimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooter',
            name='images',
        ),
        migrations.AddField(
            model_name='scooter',
            name='frontimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/bikes'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='rearimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/bikes'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='sideimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/bikes'),
        ),
    ]
