# Generated by Django 4.0.2 on 2022-03-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0007_remove_scooter_images_scooter_frontimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='frontimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/scooter'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='rearimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/scooter'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='sideimg',
            field=models.ImageField(blank=True, null=True, upload_to='img/scooter'),
        ),
    ]
