# Generated by Django 4.0.2 on 2022-03-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0008_alter_scooter_frontimg_alter_scooter_rearimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='b_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='b_id'),
        ),
        migrations.AddField(
            model_name='car',
            name='c_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='c_id'),
        ),
        migrations.AddField(
            model_name='scooter',
            name='s_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='s_id'),
        ),
    ]
