# Generated by Django 4.0.2 on 2022-03-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0009_bike_b_id_car_c_id_scooter_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='b_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='b_id'),
        ),
        migrations.AlterField(
            model_name='car',
            name='c_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='c_id'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='s_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='s_id'),
        ),
    ]
