# Generated by Django 4.0.2 on 2022-03-22 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0010_alter_bike_b_id_alter_car_c_id_alter_scooter_s_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='id',
        ),
        migrations.RemoveField(
            model_name='car',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scooter',
            name='id',
        ),
        migrations.AlterField(
            model_name='bike',
            name='b_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='b_id'),
        ),
        migrations.AlterField(
            model_name='car',
            name='c_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='c_id'),
        ),
        migrations.AlterField(
            model_name='scooter',
            name='s_id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='s_id'),
        ),
    ]
