# Generated by Django 4.0.2 on 2022-03-22 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0012_alter_bike_b_id_alter_car_c_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scooter',
            name='s_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='s_id'),
        ),
    ]
