# Generated by Django 4.0.2 on 2022-05-17 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electrovec', '0014_extendeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(primary_key=True,
                 serialize=False, verbose_name='id')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('price', models.CharField(blank=True,
                 max_length=60, null=True, verbose_name='price')),
                ('top_speed', models.CharField(
                    max_length=60, verbose_name='top speed')),
                ('range', models.CharField(max_length=60, verbose_name='range')),
                ('charging_time', models.CharField(
                    max_length=60, verbose_name='charging time')),
                ('colors', models.CharField(blank=True,
                 max_length=60, null=True, verbose_name='colors')),
                ('rating', models.CharField(blank=True,
                 max_length=60, null=True, verbose_name='rating')),
                ('description', models.TextField(blank=True,
                 max_length=1000, null=True, verbose_name='description')),
                ('frontimg', models.ImageField(
                    blank=True, null=True, upload_to='img/')),
                ('rearimg', models.ImageField(
                    blank=True, null=True, upload_to='img/')),
                ('sideimg', models.ImageField(
                    blank=True, null=True, upload_to='img/')),
                ('offers', models.CharField(blank=True,
                 max_length=180, null=True, verbose_name='offers')),
                ('battery_type', models.CharField(blank=True,
                 max_length=180, null=True, verbose_name='battery type')),
                ('max_power', models.CharField(blank=True,
                 max_length=180, null=True, verbose_name='max power')),
                ('speedometer', models.CharField(blank=True,
                 max_length=180, null=True, verbose_name='speedometer')),
                ('category', models.ForeignKey(choices=[('Bike', 'Bike'), ('Scooter', 'Scooter'), (
                    'Car', 'Car')], on_delete=django.db.models.deletion.SET_DEFAULT, to='electrovec.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Bike',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RemoveField(
            model_name='extendeduser',
            name='user',
        ),
        migrations.DeleteModel(
            name='Scooter',
        ),
        migrations.DeleteModel(
            name='ExtendedUser',
        ),
        migrations.AddField(
            model_name='cart',
            name='vehicle',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='electrovec.vehicle'),
        ),
    ]
