# Generated by Django 4.0.2 on 2022-05-17 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0017_alter_category_name_alter_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(choices=[('Bike', 'Bike'), ('Scooter', 'Scooter'), (
                'Car', 'Car')], on_delete=django.db.models.deletion.CASCADE, to='electrovec.category'),
        ),
    ]
