# Generated by Django 4.0.2 on 2022-05-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0020_alter_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
