# Generated by Django 4.0.2 on 2022-05-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0021_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_DEFAULT, to='electrovec.category'),
        ),
    ]
