# Generated by Django 4.0.2 on 2022-05-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0023_alter_category_name_alter_vehicle_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
