# Generated by Django 4.0.2 on 2022-05-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0029_v_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='v_comment',
            name='replied_to',
            field=models.IntegerField(null=True, verbose_name='replied_to'),
        ),
    ]
