# Generated by Django 4.0.2 on 2022-05-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0030_v_comment_replied_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v_comment',
            name='replied_to',
            field=models.CharField(max_length=180, null=True, verbose_name='replied_to'),
        ),
    ]
