# Generated by Django 4.0.2 on 2022-05-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0031_alter_v_comment_replied_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='v_comment',
            name='comment',
            field=models.CharField(max_length=180),
        ),
    ]
