# Generated by Django 4.0.2 on 2022-05-24 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0033_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='email',
        ),
    ]
