# Generated by Django 4.0.2 on 2022-05-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0034_remove_userdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
