# Generated by Django 4.0.2 on 2022-06-07 06:28

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0036_alter_userdetails_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=120, verbose_name='name')),
                ('price', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
            ],
        ),
    ]
