# Generated by Django 4.0.2 on 2022-07-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrovec', '0037_tempclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tempclass',
        ),
    ]
